//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingTestSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_TK
    {
        public string STXH { get; set; }
        public string BH { get; set; }
        public string TKLX { get; set; }
        public string STLX { get; set; }
        public string STSX { get; set; }
        public string STTX { get; set; }
        public string STFL { get; set; }
        public string STNRH { get; set; }
        public string STNRZ { get; set; }
        public string XZDAAH { get; set; }
        public string XZDABH { get; set; }
        public string XZDACH { get; set; }
        public string XZDADH { get; set; }
        public string XZDAAZ { get; set; }
        public string XZDABZ { get; set; }
        public string XZDACZ { get; set; }
        public string XZDADZ { get; set; }
        public string STTP { get; set; }
        public string STDA { get; set; }
        public string SYCX { get; set; }
        public string KSYY { get; set; }
        public string PROV { get; set; }
        public string STBJ { get; set; }
    }
}
